version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "50051:50051"
    volumes:
      - .:/go/src/
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
